// Spacing Tokens
// Generated by setup script
// Last Updated: {{LAST_UPDATED}}

/**
 * Spacing Scale
 * Using rem units based on 4px increments.
 * Base: 1rem = 16px
 */
export const spacing = {
  0: '0',
  px: '1px',
  0.5: '0.125rem', // 2px
  1: '0.25rem', // 4px
  1.5: '0.375rem', // 6px
  2: '0.5rem', // 8px
  2.5: '0.625rem', // 10px
  3: '0.75rem', // 12px
  3.5: '0.875rem', // 14px
  4: '1rem', // 16px
  5: '1.25rem', // 20px
  6: '1.5rem', // 24px
  7: '1.75rem', // 28px
  8: '2rem', // 32px
  9: '2.25rem', // 36px
  10: '2.5rem', // 40px
  11: '2.75rem', // 44px
  12: '3rem', // 48px
  14: '3.5rem', // 56px
  16: '4rem', // 64px
  20: '5rem', // 80px
  24: '6rem', // 96px
  28: '7rem', // 112px
  32: '8rem', // 128px
  36: '9rem', // 144px
  40: '10rem', // 160px
  44: '11rem', // 176px
  48: '12rem', // 192px
  52: '13rem', // 208px
  56: '14rem', // 224px
  60: '15rem', // 240px
  64: '16rem', // 256px
  72: '18rem', // 288px
  80: '20rem', // 320px
  96: '24rem', // 384px
}

/**
 * Section Spacing
 * Standard vertical padding for page sections.
 */
export const sectionSpacing = {
  // Mobile-first, scales up on larger screens
  sm: {
    mobile: spacing[12], // 48px
    tablet: spacing[16], // 64px
    desktop: spacing[20], // 80px
  },
  md: {
    mobile: spacing[16], // 64px
    tablet: spacing[20], // 80px
    desktop: spacing[24], // 96px
  },
  lg: {
    mobile: spacing[20], // 80px
    tablet: spacing[24], // 96px
    desktop: spacing[32], // 128px
  },
}

/**
 * Container Max Widths
 */
export const containerWidths = {
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px',
}

/**
 * Component Spacing Presets
 * Standard spacing patterns for common components.
 */
export const componentSpacing = {
  // Card padding
  card: {
    sm: spacing[4], // 16px
    md: spacing[6], // 24px
    lg: spacing[8], // 32px
  },

  // Button padding (horizontal)
  buttonX: {
    sm: spacing[3], // 12px
    md: spacing[4], // 16px
    lg: spacing[6], // 24px
  },

  // Button padding (vertical)
  buttonY: {
    sm: spacing[1.5], // 6px
    md: spacing[2], // 8px
    lg: spacing[3], // 12px
  },

  // Input padding
  input: {
    x: spacing[3], // 12px
    y: spacing[2], // 8px
  },

  // Stack spacing (gap between stacked elements)
  stack: {
    sm: spacing[2], // 8px
    md: spacing[4], // 16px
    lg: spacing[6], // 24px
  },

  // Inline spacing (gap between inline elements)
  inline: {
    sm: spacing[1], // 4px
    md: spacing[2], // 8px
    lg: spacing[4], // 16px
  },
}

/**
 * Border Radius
 */
export const borderRadius = {
  none: '0',
  sm: '0.125rem', // 2px
  DEFAULT: '0.25rem', // 4px
  md: '0.375rem', // 6px
  lg: '0.5rem', // 8px
  xl: '0.75rem', // 12px
  '2xl': '1rem', // 16px
  '3xl': '1.5rem', // 24px
  full: '9999px',
}
